exclude: '^(\.tox|\.env|dist|\.vscode)(/|$)'
repos:
  - repo: local
    hooks:
      - id: copyright-check
        name: "Copyright Check"
        types: [python]
        entry: |
          python -m scripts.copyright -s "#" -d scripts -d msts -g "*.py" -g "*.pyi" -l "LGPL3.md.jinja2"
        language: system
        pass_filenames: false
        verbose: true

  - repo: https://github.com/PyCQA/autoflake
    rev: "v2.0.1"
    hooks:
      - id: autoflake
        args:
          [
            --jobs,
            "32",
            --remove-all-unused-imports,
            --in-place,
            --expand-star-imports,
          ]

  - repo: https://github.com/myint/docformatter
    rev: "v1.5.1"
    hooks:
      - id: docformatter
        args:
          [--in-place, -r, --wrap-summaries, "88", --wrap-descriptions, "88"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier

  - repo: https://github.com/timothycrosley/isort
    rev: "5.12.0"
    hooks:
      - id: isort

  - repo: https://github.com/timothycrosley/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        args: [-a, "from __future__ import annotations", cssfinder]

  - repo: https://github.com/ambv/black
    rev: "23.1.0"
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      - id: check-toml
      # - id: check-json
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace
      - id: debug-statements

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
